### ISSUE TITLE
Website not loading properly?

### ISSUE THREAD

**Issue by principlesx** [mwinkler/TonieBox.CreativeManager#2]
I realy like the idea of your product, seems to be awsome. 

Are there any preconditions to be aware of when running your container (besides the .env)?  I just get redirected to http://localhost:5995/user/select and the websites stay's blank..
Do you have an idea?

Thanks for your support... 

Docker output:
Attaching to tonieboxcreativemanager_app_1
app_1  | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
app_1  |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
app_1  | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
app_1  |       No XML encryptor configured. Key {17f512a0-ea65-4f50-b965-a79ade958e0f} may be persisted to storage in unencrypted form.
app_1  | info: Microsoft.Hosting.Lifetime[0]
app_1  |       Now listening on: http://[::]:80
app_1  | info: Microsoft.Hosting.Lifetime[0]
app_1  |       Application started. Press Ctrl+C to shut down.
app_1  | info: Microsoft.Hosting.Lifetime[0]
app_1  |       Hosting environment: Production
app_1  | info: Microsoft.Hosting.Lifetime[0]
app_1  |       Content root path: /app
app_1  | Using '/var/media' for library root

**Comment by mwinkler** [comment]
Hi @principlesx 
There needs to be a json configuration file `creative-tonie-manager.json` in the root of your library directory with the following structure:
```
{
    "TonieMappings": [],
    "Users": [
      {
        "Id": "1",
        "Name": "User 1",
        "Credits": 0,
        "ProfileImageUrl": "https://images.assetsdelivery.com/compings_v2/topphotoengineer/topphotoengineer1603/topphotoengineer160300054.jpg",
        "Tonies": [
          "A459470E500304E0",
          "BCC73C0D500304E0",
          "F8F8F60D500304E0",
          "7D01A90C500304E0"
        ]
      },
      {
        "Id": "2",
        "Name": "User 2",
        "Credits": 0,
        "ProfileImageUrl": "https://www.gmcrafts.co.uk/wp-content/uploads/2018/11/Cute-Unicorn-Main-Product-Image.jpg",
        "Tonies": [
          "7ED3A00D500304E0",
          "A1A1510E500304E0",
          "5DDF180D500304E0",
          "6F78210C500304E0"
        ]
      }
    ],
    "Vouchers": [
      {
        "Code": "🐵🐵🐵",
        "Value": 1,
        "Used": null
      }
    ]
  }
```
I have to say, that the project is strongly customized for the handling with my kids.
It has a build in shop system, in witch they have to buy/unlock the content by receiving credits via vouchers (I printed them out).
3 credit to buy a item.
1 credit to copy a item to a creative tonie.

**Comment by principlesx** [comment]
Hi @mwinkler,

Thanks for your quick reply.

With the `creative-tonie-manager.json` it worked well.

You created an awesome tool! Congratulations to your idea and realization.
