### ISSUE TITLE
File Upload doesn't work anymore

### ISSUE THREAD

**Issue by flomader** [mwinkler/TonieBox.CreativeManager#4]
The upload to AWS doesn't work anymore.

Tried the UploadFile Test but I am getting the error:

    System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.

**Comment by flomader** [comment]
[capture.zip](https://github.com/mwinkler/TonieBox.CreativeManager/files/8882234/capture.zip)
Here is also a Fiddler capture from a successful request done with the myTonies App and an unsuccessful request done by executing the UploadFile in VS. The requests look quite different.

**Comment by mwinkler** [comment]
Thanks for having a look.
Unfortunately, I'm not actively using the project at the moment, since my kids are a bit older now.

**Comment by gemse007** [comment]
You probably should close the bug, as it has been fixed.
Anyhow - I really love your project and as you wrote that you don't want to invest more time in it - I've created a branch and tried myself to make some improvements. Based on your code.
Hope that is okay for you. As I'm new to github and don't know how to reach you - I'm writing here - you can delete it if you want.
My branch if you want to take a look: [https://github.com/gemse007/TonieBox.CreativeManager/]

**Comment by mwinkler** [comment]
@gemse007 Thank you for the response. Fell free to use and improve this project. It is a pleasure for me when others use it. Best regards
